modLoader="javafml"
loaderVersion="[31,)"
license="All rights reserved"
issueTrackerURL="https://github.com/TrueGkoliver/DevsideTools/issues"

[[mods]]
modId="devsidetools"
version="1.3.1"
displayName="Devside Tools"
credits="Team Aurora"
authors="Gkoliver"
description="More commands for better devleopment"

[[dependencies.devsidetools]]
    modId="forge"
    mandatory=true
    versionRange="[32.0.75,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.devsidetools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1,)"
    ordering="NONE"
    side="BOTH"
